# spring
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playbaseball?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: create
server:
  servlet:
    context-path: /playBaseBall
springdoc:
  api-docs:
    path: /v3/api-docs # API 명세 JSON 경로
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method # UI에서 정렬 기준 설정
    tagsSorter: alpha # 태그 알파벳 순 정렬
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false